#!/usr/bin/env python3
"""Build Tico HQ's copy of the org builder catalog, and of the recommender that reads it.

Tico HQ (hq/) is its own image with no templates in it, so it serves suggestions from two generated files:

    hq/catalog.json       departments and card metadata (no instructions), from templates/departments.yaml and
                          templates/catalog/*/card.yaml, built with backend/recruit_rank.py `build()`, the same
                          function the Tico server uses for its own catalog
    hq/recruit_rank.py    a copy of backend/recruit_rank.py, the local recommender both sides fall back to

    python3 scripts/build_catalog_json.py           # rewrite both
    python3 scripts/build_catalog_json.py --check   # exit 1 when either is stale (a test runs this)

Run it after changing a card, departments.yaml or backend/recruit_rank.py.
"""
import importlib.util
import json
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
TEMPLATES = ROOT / "templates"
SOURCE = ROOT / "backend" / "recruit_rank.py"
OUT_CATALOG = ROOT / "hq" / "catalog.json"
OUT_RANKER = ROOT / "hq" / "recruit_rank.py"
HEADER = "# Generated by scripts/build_catalog_json.py from backend/recruit_rank.py. Do not edit; edit that file.\n"


def _ranker():
    spec = importlib.util.spec_from_file_location("recruit_rank_source", SOURCE)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def cards(catalog_dir=TEMPLATES / "catalog"):
    out = []
    for card in sorted(Path(catalog_dir).glob("*/card.yaml")):
        try:
            document = yaml.safe_load(card.read_text())
        except yaml.YAMLError:
            continue
        if isinstance(document, dict):
            out.append(document)
    return out


def build():
    departments = yaml.safe_load((TEMPLATES / "departments.yaml").read_text()) or {}
    catalog = _ranker().build(departments, cards())
    return json.dumps(catalog, indent=1, ensure_ascii=False, sort_keys=True) + "\n", HEADER + SOURCE.read_text()


def main(argv):
    catalog, ranker = build()
    if "--check" in argv:
        stale = [str(path.relative_to(ROOT)) for path, text in ((OUT_CATALOG, catalog), (OUT_RANKER, ranker))
                 if not path.is_file() or path.read_text() != text]
        if stale:
            print("stale: " + ", ".join(stale) + "; run python3 scripts/build_catalog_json.py", file=sys.stderr)
            return 1
        return 0
    OUT_CATALOG.parent.mkdir(exist_ok=True)
    OUT_CATALOG.write_text(catalog)
    OUT_RANKER.write_text(ranker)
    print("%s, %s" % (OUT_CATALOG.relative_to(ROOT), OUT_RANKER.relative_to(ROOT)))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
